require "import"
import "android.app.*"
import "android.os.*"
import "android.widget.*"
import "android.view.*"

--import "muk"
--删掉“--”注释符号以使用中文函数

--程序启动时会执行的事件
--程序启动时会执行的事件
require "import"
import "android.widget.EditText"
import "android.widget.LinearLayout"
layout={ LinearLayout;
  layout_height="fill";
  layout_width="fill";
  {
    LinearLayout;
    layout_width="fill";
    layout_height="fill";
    Orientation="vertical";

    {
      LinearLayout;
      layout_gravity="bottom";
      layout_width="fill";
      orientation="horizontal";
      layout_height="70dp";
      {
        LinearLayout;
        layout_weight="1";
        layout_height="fill";
        background="#FFB0A4E3";

      };
      {
        LinearLayout;
        layout_weight="1";
        layout_height="fill";
        background="#FFB0A4E3";

      };

    };
    {
      PageView;
      background="#fafafafa";
      id="huadong";
      pages={
        {
          ScrollView;
          background="#ffeeeeee";
          {
            LinearLayout;
            layout_width="fill";
            layout_height="fill";
            Orientation="vertical";
            {
              CardView;
              layout_width="fill";
              id="card";
              layout_height="0dp";
              layout_marginTop="0dp";
              layout_marginLeft="0dp";
              layout_marginRight="0dp";
              layout_marginBottom="0dp";
              {
                LinearLayout;
                layout_width="fill";
                layout_height="fill";
                Orientation="vertical";
                {
                  TextView;
                  gravity="center";
                  layout_gravity="center";
                  text=[==[A box]==];
                };
                {
                  LinearLayout;
                  layout_width="fill";
                  layout_height="fill";
                  Orientation="horizontal";
                  {
                    LinearLayout;
                    id="fengxiang";
                    layout_weight="1";
                    layout_height="fill";
                    gravity="center";
                    {
                      ImageView;
                      src="share_variant_48x48.png";
                    };
                  };
                  {
                    LinearLayout;
                    id="shoucang";
                    layout_weight="1";
                    layout_height="fill";
                    gravity="center";
                    {
                      ImageView;
                      src="star_half_48x48.png";
                    };
                  };
                  {
                    LinearLayout;
                    id="yuanma";
                    layout_weight="1";
                    layout_height="fill";
                    gravity="center";
                    {
                      ImageView;
                      src="apple_mobileme_48x48.png";
                    };
                  };
                };
              };
            };
            {
              CardView;
              layout_width="fill";
              id="card1";
              layout_height="200dp";
              layout_marginTop="10dp";
              background="#ffffffff";
              layout_marginLeft="10dp";
              layout_marginRight="10dp";
              layout_marginBottom="10dp";
              {
                LinearLayout;
                layout_width="fill";
                layout_height="fill";
                Orientation="vertical";
                {
                  TextView;
                  layout_width="100dp";
                  layout_height="40dp";
                  gravity="center";
                  text="开发相关";
                  textColor="#FFB0A4E3";
                  textSize="18dp";
                };
                {
                  LinearLayout;
                  id="kaifazhe";
                  layout_width="fill";
                  gravity="center|left";
                  orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="banben.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                   layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="版本";
                      textColor="#566270";
                      textSize="15sp";
                    };
                    {
                      TextView;
                      text="版本号";
                      textColor="#FFB0A4E3";
                      textSize="12sp";
                    };
                  };
                };
                {
                  LinearLayout;
                  id="kuanid";
                  layout_width="fill";
                  gravity="center|left";
                  orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="zuozhe.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="";

                      textColor="#566270";
                      textSize="15sp";
                    };
                    {
                      TextView;
                      text="APP开发者";
                      textColor="#FFB0A4E3";
                      textSize="12sp";
                    };
                  };
                };
                {
                  LinearLayout;
                  id="tubiao";
                  layout_width="fill";
                  gravity="center|left";
                  orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="account.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="作者QQ";
                      textColor="#566270";
                      textSize="15sp";
                    };
                    {
                      TextView;
                      text="63";
                      textColor="#FFB0A4E3";
                      textSize="12sp";
                    };
                  };
                };
              };
            };
            {
              CardView;
              layout_width="fill";
              id="card2";
              layout_height="240dp";
              layout_marginTop="10dp";
              background="#ffffffff";
              layout_marginLeft="10dp";
              layout_marginRight="10dp";
              layout_marginBottom="10dp";
              {
                LinearLayout;
                layout_width="fill";
                layout_height="fill";
                Orientation="vertical";
                {
                  TextView;
                  layout_width="120dp";
                  layout_height="40dp";
                  gravity="center";
                  text="联系与反馈";
                  textColor="#FFB0A4E3";
                  textSize="18dp";
                };
                {
                  LinearLayout;
                  id="zeng";
                  layout_width="fill";
                  gravity="center|left";
                  Orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="juanzeng.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="作者QQ";
                      textColor="#566270";
                      textSize="15dp";
                    };

                  };
                };
                {
                  LinearLayout;
                  id="lianxi";
                  layout_width="fill";
                  gravity="center|left";
                  Orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="qun.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="邮箱";
                      textColor="#566270";
                      textSize="15dp";
                    };
                  };
                };
                {
                  LinearLayout;
                  id="youjian";
                  layout_width="fill";
                  gravity="center|left";
                  Orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="document_48x48.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="网站";
                      textColor="#566270";
                      textSize="15dp";
                    };
                  };
                };
                {
                  LinearLayout;
                  id="qqun";
                  layout_width="fill";
                  gravity="center|left";
                  Orientation="horizontal";
                  {
                    ImageView;
                    layout_width="30dp";
                    layout_margin="10dp";
                    layout_height="30dp";
                    src="linux_48x48.png";
                  };
                  {
                    LinearLayout;
                    layout_width="fill";
                    layout_marginLeft="10dp";
                    layout_marginRight="10dp";
                    orientation="vertical";
                    {
                      TextView;
                      text="Q群交流:654675889";
                      textColor="#566270";
                      textSize="15dp";
                    };
                  };
                };
              };
            };
            {
              CardView;
              layout_width="fill";
              id="card2";
              layout_height="300dp";
              layout_marginTop="10dp";
              background="#ffffffff";
              layout_marginLeft="10dp";
              layout_marginRight="10dp";
              layout_marginBottom="10dp";
              {
                LinearLayout;
                layout_width="fill";
                layout_height="fill";
                Orientation="vertical";
                {
                  TextView;
                  layout_width="70dp";
                  layout_height="40dp";
                  gravity="center";
                  text="声明";
                  textColor="#FFB0A4E3";
                  textSize="18dp";
                };
                {
                  TextView;
                  layout_width="fill";
                  layout_height="fill";
                  layout_marginTop="10dp";
                  layout_marginLeft="20dp";
                  layout_marginRight="20dp";
                  text=[==[温馨提示:
本软件功能均来自于网页
本软件内涉及的教程及内容版权均归于网页原作者
侵权请联系网页原作者，本软件仅供学习，禁止使用违法行为
本软件作者不承担任何法律责任
感谢本软件内涉及到和使用到的内容页
最终解释权归本软件作者所有
          ]==];
                };
              };
            };
          };
        };
      };
      layout_weight="1";
    };
  };
};


activity.setContentView(loadlayout(layout))
--把这段代码放到调试里面去测试
if Build.VERSION.SDK_INT >= 19 then
  activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
end

--设置滑动条&字体颜色




